// <auto-generated />
namespace Mac_Movie_Store.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class myMirgrationName : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(myMirgrationName));
        
        string IMigrationMetadata.Id
        {
            get { return "201908140100314_myMirgrationName"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
